theme: jekyll-theme-architect

<script>
document.cookie = "session=test GDPR"; 
document.cookie = "favorite_task=collect Data"; 
functionalertCookie() { alert(document.cookie); } </script>
<body> Bine aivenit la lab <button onclick="alertCookie()">Show cookies</button></body>